### ISSUE TITLE
uncalled genotype issue

### ISSUE THREAD

**Issue by ArashBayatDev** [aehrc/VariantSpark#164] opened 2020-08-25 01:06 UTC
the "fit_trees" function (Hail Interface) fails with error when there are uncalled genotype.
However the error does not mentioned what is the source of the problem. 
I recommend to check for this situation and print a proper error message for the user

**Comment by piotrszul** [comment] 2020-12-18 02:12
Duplicate of #139

**Closed as completed by piotrszul** 2020-12-18 02:12 UTC
